/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Modelo;

import java.util.Date;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author mateu
 */
public class GestionAlta extends javax.swing.JDialog {
   DefaultTableModel dtm= new DefaultTableModel();
   PantallaPrincipal pp= new PantallaPrincipal();

    /**
     * Creates new form GestionAlta
     */
    public GestionAlta(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.pp=(PantallaPrincipal) parent;
    }
    
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1Importe = new javax.swing.JLabel();
        jLabel2Concepto = new javax.swing.JLabel();
        jTextField2Concepto = new javax.swing.JTextField();
        jButton1Confirmar = new javax.swing.JButton();
        jFormattedTextField1Importe = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1Importe.setText("Importe:");

        jLabel2Concepto.setText("Concepto:");

        jTextField2Concepto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ConceptoActionPerformed(evt);
            }
        });

        jButton1Confirmar.setText("Confirmar");
        jButton1Confirmar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1ConfirmarMouseClicked(evt);
            }
        });
        jButton1Confirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ConfirmarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2Concepto, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1Importe, javax.swing.GroupLayout.Alignment.LEADING))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField2Concepto, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(jFormattedTextField1Importe))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(249, Short.MAX_VALUE)
                .addComponent(jButton1Confirmar)
                .addGap(72, 72, 72))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1Importe)
                    .addComponent(jFormattedTextField1Importe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2Concepto)
                    .addComponent(jTextField2Concepto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(81, 81, 81)
                .addComponent(jButton1Confirmar)
                .addContainerGap(83, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField2ConceptoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ConceptoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ConceptoActionPerformed

    private void jButton1ConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ConfirmarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ConfirmarActionPerformed

    private void jButton1ConfirmarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1ConfirmarMouseClicked
        // TODO add your handling code here:
       
       IngresoGasto operacion=new IngresoGasto( "kakaksa",jTextField2Concepto.getText(),Integer.parseInt(jFormattedTextField1Importe.getText()) );
        pp.anadirIngreso(operacion);
       dispose();
        
    }//GEN-LAST:event_jButton1ConfirmarMouseClicked

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1Confirmar;
    private javax.swing.JFormattedTextField jFormattedTextField1Importe;
    private javax.swing.JLabel jLabel1Importe;
    private javax.swing.JLabel jLabel2Concepto;
    private javax.swing.JTextField jTextField2Concepto;
    // End of variables declaration//GEN-END:variables
}
